import { Product } from '@/types'

// Mock данные для демонстрации (пока нет backend)
export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Ноутбук Apple MacBook Pro 14" M3',
    slug: 'macbook-pro-14-m3',
    category: 1,
    category_name: 'Ноутбуки',
    brand: 1,
    brand_name: 'Apple',
    description: 'Мощный ноутбук для профессионалов',
    short_description: 'MacBook Pro 14" с чипом M3',
    price: 850000,
    old_price: 950000,
    discount_percentage: 11,
    sku: 'MBP-14-M3',
    stock: 10,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.9,
    reviews_count: 156,
    is_new: false,
    is_featured: true,
    views_count: 2341,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 2,
    name: 'Смартфон Samsung Galaxy S24 Ultra 12/256GB',
    slug: 'samsung-s24-ultra',
    category: 2,
    category_name: 'Смартфоны',
    brand: 2,
    brand_name: 'Samsung',
    description: 'Флагманский смартфон Samsung',
    short_description: 'Galaxy S24 Ultra с S Pen',
    price: 520000,
    old_price: 580000,
    discount_percentage: 10,
    sku: 'S24-ULTRA-256',
    stock: 15,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.8,
    reviews_count: 234,
    is_new: true,
    is_featured: true,
    views_count: 3421,
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: 3,
    name: 'Наушники Apple AirPods Pro 2',
    slug: 'airpods-pro-2',
    category: 3,
    category_name: 'Аксессуары',
    brand: 1,
    brand_name: 'Apple',
    description: 'Беспроводные наушники с активным шумоподавлением',
    short_description: 'AirPods Pro 2 с USB-C',
    price: 120000,
    old_price: 135000,
    discount_percentage: 11,
    sku: 'APP-2-USBC',
    stock: 25,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.9,
    reviews_count: 445,
    is_new: false,
    is_featured: true,
    views_count: 5621,
    created_at: '2024-01-05',
    updated_at: '2024-01-05',
  },
  {
    id: 4,
    name: 'Клавиатура Logitech MX Keys',
    slug: 'logitech-mx-keys',
    category: 3,
    category_name: 'Аксессуары',
    brand: 3,
    brand_name: 'Logitech',
    description: 'Беспроводная клавиатура для продуктивности',
    short_description: 'MX Keys с подсветкой',
    price: 45000,
    old_price: null,
    discount_percentage: 0,
    sku: 'MX-KEYS',
    stock: 30,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.7,
    reviews_count: 189,
    is_new: false,
    is_featured: false,
    views_count: 1234,
    created_at: '2024-01-10',
    updated_at: '2024-01-10',
  },
  {
    id: 5,
    name: 'Мышь Logitech MX Master 3S',
    slug: 'logitech-mx-master-3s',
    category: 3,
    category_name: 'Аксессуары',
    brand: 3,
    brand_name: 'Logitech',
    description: 'Эргономичная беспроводная мышь',
    short_description: 'MX Master 3S для профессионалов',
    price: 38000,
    old_price: 42000,
    discount_percentage: 10,
    sku: 'MX-M3S',
    stock: 20,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.8,
    reviews_count: 312,
    is_new: false,
    is_featured: true,
    views_count: 2156,
    created_at: '2024-01-08',
    updated_at: '2024-01-08',
  },
  {
    id: 6,
    name: 'Монитор Dell UltraSharp 27" 4K',
    slug: 'dell-ultrasharp-27-4k',
    category: 4,
    category_name: 'Мониторы',
    brand: 4,
    brand_name: 'Dell',
    description: 'Профессиональный монитор 4K',
    short_description: '27" IPS 4K монитор',
    price: 180000,
    old_price: 210000,
    discount_percentage: 14,
    sku: 'DELL-U2723DE',
    stock: 8,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.9,
    reviews_count: 98,
    is_new: true,
    is_featured: true,
    views_count: 1567,
    created_at: '2024-01-12',
    updated_at: '2024-01-12',
  },
  {
    id: 7,
    name: 'Принтер HP LaserJet Pro M404dn',
    slug: 'hp-laserjet-m404dn',
    category: 5,
    category_name: 'Принтеры',
    brand: 5,
    brand_name: 'HP',
    description: 'Лазерный принтер для офиса',
    short_description: 'Черно-белый лазерный принтер',
    price: 95000,
    old_price: null,
    discount_percentage: 0,
    sku: 'HP-M404DN',
    stock: 12,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.6,
    reviews_count: 67,
    is_new: false,
    is_featured: false,
    views_count: 876,
    created_at: '2024-01-06',
    updated_at: '2024-01-06',
  },
  {
    id: 8,
    name: 'SSD Samsung 980 PRO 1TB',
    slug: 'samsung-980-pro-1tb',
    category: 6,
    category_name: 'Накопители',
    brand: 2,
    brand_name: 'Samsung',
    description: 'Быстрый NVMe SSD',
    short_description: '1TB NVMe Gen4',
    price: 48000,
    old_price: 55000,
    discount_percentage: 13,
    sku: 'S980-1TB',
    stock: 35,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.9,
    reviews_count: 523,
    is_new: false,
    is_featured: true,
    views_count: 4234,
    created_at: '2024-01-03',
    updated_at: '2024-01-03',
  },
  {
    id: 9,
    name: 'iPhone 15 Pro Max 256GB',
    slug: 'iphone-15-pro-max',
    category: 2,
    category_name: 'Смартфоны',
    brand: 1,
    brand_name: 'Apple',
    description: 'Флагманский смартфон Apple',
    short_description: 'iPhone 15 Pro Max Титан',
    price: 680000,
    old_price: 750000,
    discount_percentage: 9,
    sku: 'IP15PM-256',
    stock: 5,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.9,
    reviews_count: 678,
    is_new: true,
    is_featured: true,
    views_count: 8934,
    created_at: '2024-01-18',
    updated_at: '2024-01-18',
  },
  {
    id: 10,
    name: 'Игровое кресло DXRacer Formula',
    slug: 'dxracer-formula',
    category: 3,
    category_name: 'Аксессуары',
    brand: 6,
    brand_name: 'DXRacer',
    description: 'Профессиональное игровое кресло',
    short_description: 'Кресло с поддержкой поясницы',
    price: 75000,
    old_price: 95000,
    discount_percentage: 21,
    sku: 'DXR-FORM',
    stock: 7,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.6,
    reviews_count: 145,
    is_new: false,
    is_featured: false,
    views_count: 956,
    created_at: '2024-01-14',
    updated_at: '2024-01-14',
  },
  {
    id: 11,
    name: 'Веб-камера Logitech StreamCam',
    slug: 'logitech-streamcam',
    category: 3,
    category_name: 'Аксессуары',
    brand: 3,
    brand_name: 'Logitech',
    description: 'Веб-камера для стриминга',
    short_description: '1080p/60fps камера',
    price: 32000,
    old_price: 38000,
    discount_percentage: 16,
    sku: 'L-SCAM',
    stock: 18,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.7,
    reviews_count: 234,
    is_new: false,
    is_featured: false,
    views_count: 1432,
    created_at: '2024-01-11',
    updated_at: '2024-01-11',
  },
  {
    id: 12,
    name: 'Ноутбук ASUS ROG Strix G15',
    slug: 'asus-rog-g15',
    category: 1,
    category_name: 'Ноутбуки',
    brand: 7,
    brand_name: 'ASUS',
    description: 'Игровой ноутбук с RTX 4060',
    short_description: 'ROG Strix с 144Hz дисплеем',
    price: 650000,
    old_price: 720000,
    discount_percentage: 10,
    sku: 'ROG-G15',
    stock: 4,
    is_available: true,
    main_image: '/logo.png',
    rating: 4.8,
    reviews_count: 267,
    is_new: true,
    is_featured: true,
    views_count: 3421,
    created_at: '2024-01-16',
    updated_at: '2024-01-16',
  },
]

